// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	labels "k8s.io/apimachinery/pkg/labels"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

func init() {
	SchemeBuilder.Register(RegisterDeepCopies)
}

// RegisterDeepCopies adds deep-copy functions to the given scheme. Public
// to allow building arbitrary schemes.
//
// Deprecated: deepcopy registration will go away when static deepcopy is fully implemented.
func RegisterDeepCopies(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedDeepCopyFuncs(
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AssignmentStates).DeepCopyInto(out.(*AssignmentStates))
			return nil
		}, InType: reflect.TypeOf(&AssignmentStates{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ClusterPodAssignmentRule).DeepCopyInto(out.(*ClusterPodAssignmentRule))
			return nil
		}, InType: reflect.TypeOf(&ClusterPodAssignmentRule{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ClusterPodAssignmentRuleList).DeepCopyInto(out.(*ClusterPodAssignmentRuleList))
			return nil
		}, InType: reflect.TypeOf(&ClusterPodAssignmentRuleList{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*NodeAssignment).DeepCopyInto(out.(*NodeAssignment))
			return nil
		}, InType: reflect.TypeOf(&NodeAssignment{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*NodeAssignmentGroup).DeepCopyInto(out.(*NodeAssignmentGroup))
			return nil
		}, InType: reflect.TypeOf(&NodeAssignmentGroup{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*NodeAssignmentGroupList).DeepCopyInto(out.(*NodeAssignmentGroupList))
			return nil
		}, InType: reflect.TypeOf(&NodeAssignmentGroupList{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*NodeAssignmentGroupSpec).DeepCopyInto(out.(*NodeAssignmentGroupSpec))
			return nil
		}, InType: reflect.TypeOf(&NodeAssignmentGroupSpec{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*NodeAssignmentGroupStatus).DeepCopyInto(out.(*NodeAssignmentGroupStatus))
			return nil
		}, InType: reflect.TypeOf(&NodeAssignmentGroupStatus{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*PackLeftScheduling).DeepCopyInto(out.(*PackLeftScheduling))
			return nil
		}, InType: reflect.TypeOf(&PackLeftScheduling{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*PodAssignmentRule).DeepCopyInto(out.(*PodAssignmentRule))
			return nil
		}, InType: reflect.TypeOf(&PodAssignmentRule{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*PodAssignmentRuleList).DeepCopyInto(out.(*PodAssignmentRuleList))
			return nil
		}, InType: reflect.TypeOf(&PodAssignmentRuleList{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*PodAssignmentRuleScheduling).DeepCopyInto(out.(*PodAssignmentRuleScheduling))
			return nil
		}, InType: reflect.TypeOf(&PodAssignmentRuleScheduling{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*PodAssignmentRuleSpec).DeepCopyInto(out.(*PodAssignmentRuleSpec))
			return nil
		}, InType: reflect.TypeOf(&PodAssignmentRuleSpec{})},
	)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentStates) DeepCopyInto(out *AssignmentStates) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentStates.
func (in *AssignmentStates) DeepCopy() *AssignmentStates {
	if in == nil {
		return nil
	}
	out := new(AssignmentStates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodAssignmentRule) DeepCopyInto(out *ClusterPodAssignmentRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodAssignmentRule.
func (in *ClusterPodAssignmentRule) DeepCopy() *ClusterPodAssignmentRule {
	if in == nil {
		return nil
	}
	out := new(ClusterPodAssignmentRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPodAssignmentRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodAssignmentRuleList) DeepCopyInto(out *ClusterPodAssignmentRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPodAssignmentRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodAssignmentRuleList.
func (in *ClusterPodAssignmentRuleList) DeepCopy() *ClusterPodAssignmentRuleList {
	if in == nil {
		return nil
	}
	out := new(ClusterPodAssignmentRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPodAssignmentRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAssignment) DeepCopyInto(out *NodeAssignment) {
	*out = *in
	if in.PackLeft != nil {
		in, out := &in.PackLeft, &out.PackLeft
		if *in == nil {
			*out = nil
		} else {
			*out = new(PackLeftScheduling)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAssignment.
func (in *NodeAssignment) DeepCopy() *NodeAssignment {
	if in == nil {
		return nil
	}
	out := new(NodeAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAssignmentGroup) DeepCopyInto(out *NodeAssignmentGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAssignmentGroup.
func (in *NodeAssignmentGroup) DeepCopy() *NodeAssignmentGroup {
	if in == nil {
		return nil
	}
	out := new(NodeAssignmentGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeAssignmentGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAssignmentGroupList) DeepCopyInto(out *NodeAssignmentGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeAssignmentGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAssignmentGroupList.
func (in *NodeAssignmentGroupList) DeepCopy() *NodeAssignmentGroupList {
	if in == nil {
		return nil
	}
	out := new(NodeAssignmentGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeAssignmentGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAssignmentGroupSpec) DeepCopyInto(out *NodeAssignmentGroupSpec) {
	*out = *in
	if in.TargetLabels != nil {
		in, out := &in.TargetLabels, &out.TargetLabels
		*out = make(labels.Set, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefaultAssignment != nil {
		in, out := &in.DefaultAssignment, &out.DefaultAssignment
		if *in == nil {
			*out = nil
		} else {
			*out = new(NodeAssignment)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Assignments != nil {
		in, out := &in.Assignments, &out.Assignments
		*out = make([]NodeAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAssignmentGroupSpec.
func (in *NodeAssignmentGroupSpec) DeepCopy() *NodeAssignmentGroupSpec {
	if in == nil {
		return nil
	}
	out := new(NodeAssignmentGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAssignmentGroupStatus) DeepCopyInto(out *NodeAssignmentGroupStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAssignmentGroupStatus.
func (in *NodeAssignmentGroupStatus) DeepCopy() *NodeAssignmentGroupStatus {
	if in == nil {
		return nil
	}
	out := new(NodeAssignmentGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackLeftScheduling) DeepCopyInto(out *PackLeftScheduling) {
	*out = *in
	if in.FullPercent != nil {
		in, out := &in.FullPercent, &out.FullPercent
		if *in == nil {
			*out = nil
		} else {
			*out = new(int)
			**out = **in
		}
	}
	if in.PercentAvoid != nil {
		in, out := &in.PercentAvoid, &out.PercentAvoid
		if *in == nil {
			*out = nil
		} else {
			*out = new(int)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackLeftScheduling.
func (in *PackLeftScheduling) DeepCopy() *PackLeftScheduling {
	if in == nil {
		return nil
	}
	out := new(PackLeftScheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAssignmentRule) DeepCopyInto(out *PodAssignmentRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAssignmentRule.
func (in *PodAssignmentRule) DeepCopy() *PodAssignmentRule {
	if in == nil {
		return nil
	}
	out := new(PodAssignmentRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodAssignmentRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAssignmentRuleList) DeepCopyInto(out *PodAssignmentRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodAssignmentRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAssignmentRuleList.
func (in *PodAssignmentRuleList) DeepCopy() *PodAssignmentRuleList {
	if in == nil {
		return nil
	}
	out := new(PodAssignmentRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodAssignmentRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAssignmentRuleScheduling) DeepCopyInto(out *PodAssignmentRuleScheduling) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.Affinity)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAssignmentRuleScheduling.
func (in *PodAssignmentRuleScheduling) DeepCopy() *PodAssignmentRuleScheduling {
	if in == nil {
		return nil
	}
	out := new(PodAssignmentRuleScheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAssignmentRuleSpec) DeepCopyInto(out *PodAssignmentRuleSpec) {
	*out = *in
	if in.TargetLabels != nil {
		in, out := &in.TargetLabels, &out.TargetLabels
		*out = make(labels.Set, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAssignmentRuleSpec.
func (in *PodAssignmentRuleSpec) DeepCopy() *PodAssignmentRuleSpec {
	if in == nil {
		return nil
	}
	out := new(PodAssignmentRuleSpec)
	in.DeepCopyInto(out)
	return out
}
