/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	assignments_v1alpha1 "github.com/domoinc/kube-valet/pkg/apis/assignments/v1alpha1"
	versioned "github.com/domoinc/kube-valet/pkg/client/clientset/versioned"
	internalinterfaces "github.com/domoinc/kube-valet/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/domoinc/kube-valet/pkg/client/listers/assignments/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ClusterPodAssignmentRuleInformer provides access to a shared informer and lister for
// ClusterPodAssignmentRules.
type ClusterPodAssignmentRuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterPodAssignmentRuleLister
}

type clusterPodAssignmentRuleInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewClusterPodAssignmentRuleInformer constructs a new informer for ClusterPodAssignmentRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterPodAssignmentRuleInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.AssignmentsV1alpha1().ClusterPodAssignmentRules().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.AssignmentsV1alpha1().ClusterPodAssignmentRules().Watch(options)
			},
		},
		&assignments_v1alpha1.ClusterPodAssignmentRule{},
		resyncPeriod,
		indexers,
	)
}

func defaultClusterPodAssignmentRuleInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewClusterPodAssignmentRuleInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *clusterPodAssignmentRuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&assignments_v1alpha1.ClusterPodAssignmentRule{}, defaultClusterPodAssignmentRuleInformer)
}

func (f *clusterPodAssignmentRuleInformer) Lister() v1alpha1.ClusterPodAssignmentRuleLister {
	return v1alpha1.NewClusterPodAssignmentRuleLister(f.Informer().GetIndexer())
}
