/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	assignments_v1alpha1 "github.com/domoinc/kube-valet/pkg/apis/assignments/v1alpha1"
	versioned "github.com/domoinc/kube-valet/pkg/client/clientset/versioned"
	internalinterfaces "github.com/domoinc/kube-valet/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/domoinc/kube-valet/pkg/client/listers/assignments/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// NodeAssignmentGroupInformer provides access to a shared informer and lister for
// NodeAssignmentGroups.
type NodeAssignmentGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NodeAssignmentGroupLister
}

type nodeAssignmentGroupInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewNodeAssignmentGroupInformer constructs a new informer for NodeAssignmentGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodeAssignmentGroupInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.AssignmentsV1alpha1().NodeAssignmentGroups().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.AssignmentsV1alpha1().NodeAssignmentGroups().Watch(options)
			},
		},
		&assignments_v1alpha1.NodeAssignmentGroup{},
		resyncPeriod,
		indexers,
	)
}

func defaultNodeAssignmentGroupInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewNodeAssignmentGroupInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *nodeAssignmentGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&assignments_v1alpha1.NodeAssignmentGroup{}, defaultNodeAssignmentGroupInformer)
}

func (f *nodeAssignmentGroupInformer) Lister() v1alpha1.NodeAssignmentGroupLister {
	return v1alpha1.NewNodeAssignmentGroupLister(f.Informer().GetIndexer())
}
