/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/domoinc/kube-valet/pkg/apis/assignments/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NodeAssignmentGroupLister helps list NodeAssignmentGroups.
type NodeAssignmentGroupLister interface {
	// List lists all NodeAssignmentGroups in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.NodeAssignmentGroup, err error)
	// Get retrieves the NodeAssignmentGroup from the index for a given name.
	Get(name string) (*v1alpha1.NodeAssignmentGroup, error)
	NodeAssignmentGroupListerExpansion
}

// nodeAssignmentGroupLister implements the NodeAssignmentGroupLister interface.
type nodeAssignmentGroupLister struct {
	indexer cache.Indexer
}

// NewNodeAssignmentGroupLister returns a new NodeAssignmentGroupLister.
func NewNodeAssignmentGroupLister(indexer cache.Indexer) NodeAssignmentGroupLister {
	return &nodeAssignmentGroupLister{indexer: indexer}
}

// List lists all NodeAssignmentGroups in the indexer.
func (s *nodeAssignmentGroupLister) List(selector labels.Selector) (ret []*v1alpha1.NodeAssignmentGroup, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NodeAssignmentGroup))
	})
	return ret, err
}

// Get retrieves the NodeAssignmentGroup from the index for a given name.
func (s *nodeAssignmentGroupLister) Get(name string) (*v1alpha1.NodeAssignmentGroup, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("nodeassignmentgroup"), name)
	}
	return obj.(*v1alpha1.NodeAssignmentGroup), nil
}
